import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

// Import the Inter font
const inter = Inter({ subsets: ['latin'] });

// Page metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Main Home component
export default function Home() {
  return (
    <>
      <h1 className="text-3xl font-bold underline">
        Home, Next.js!
      </h1>
    </>
  );
}
